repos:
-   repo: https://github.com/python-poetry/poetry
    rev: "2.0.1"
    hooks:
    -   id: poetry-check

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    #-   id: no-commit-to-branch  # Do not allow commits to master/main branch
    -   id: check-json  # Attempts to load all json files to verify syntax
        exclude: |
            (?x)^(
                .*\.eslintrc.json
            )
    -   id: pretty-format-json  # Check all JSON files are sorted and indented (2)
    -   id: check-yaml  # Attempts to load most yaml files to verify syntax
        exclude:  |
            (?x)^(
                .*/pnpm-lock.yaml
            )
    -   id: debug-statements  # Looks for debugger imports and `breakpoint()`
    -   id: end-of-file-fixer  # Ensure ends with newline
        exclude: |
            (?x)^(
                .*/test_files/multiphase_expected|
                \.ts|
                \.tsx
            )
        # args: [--remove]  # Remove the coding pragma (useful for py3-only codebase)
    -   id: mixed-line-ending  # Replaces mixed line ending to the most common
        exclude: |
            (?x)^(
                .*/tests/files|
                .*/tests/test_files|
                \.ts|
                \.tsx
            )
    -   id: trailing-whitespace  # Trim trailing whitespace
        exclude: |
            (?x)^(
                .*/tests/files|
                .*/tests/test_files|
                \.ts|
                \.tsx
            )
    -   id: detect-private-key  # Checks for private keys
    -   id: check-merge-conflict  # Check for merge conflict strings
    -   id: name-tests-test  # Check files in tests/ end with `_test.py`
        exclude: |
            (?x)^(
                .*/tests/data_providers|
                .*/tests/tools
            )
    -   id: check-added-large-files  # Prevent giant files from being committed
        args: ['--maxkb=200']

# Quick content checks based on grepping for python specific patterns:
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa   # Prohibit overly broad QA exclusions.
    -   id: python-no-eval              # Never use eval() it's dangerous.
    -   id: python-no-log-warn          # logger.warning(), not old .warn()
    -   id: python-use-type-annotations # Enforce that python3.6+ type annotations are used instead of type comments

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort
        args: ["--settings-path", "pyproject.toml"]

-   repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    -   id: black
        args: ["--config", "pyproject.toml"]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        name: flake8 (bugbear)
        additional_dependencies: [Flake8-pyproject]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: ["--py310-plus"]

-   repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
    -   id: nbstripout
